POST http://localhost:3000/api/generate_recipe
Content-Type: application/json
Authorization: Bearer test

{
  "ingredients" : [
    "Lemon-Garlic Grilled Chicken",
    "Dried Crackers",
    "Canned Tuna",
    "Creamed Spinach",
    "Canned Corn",
    "Peas",
    "Chocolate Bar"
  ],
  "specialInstructions": "I'd like the meal to include all 3 courses"

}