import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./design.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const readexProRegular = localFont({
  src: "./fonts/ReadexPro-Regular.ttf",
  variable: "--font-readexpro-regular",
});
const readexProBold = localFont({
  src: "./fonts/ReadexPro-Bold.ttf",
  variable: "--font-readexpro-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${readexProRegular.variable} ${readexProBold.variable}`}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
